version: "3.7"

networks: #Add to my Nginx Network in Docker/Not really needed 
    default:
        external:
            name: "nginxproxymanager_default"

services:
    chibisafe:
        build:
            context: ../
            dockerfile: ./docker/chibisafe/Dockerfile
        volumes:
            - ./chibisafe-data:/usr/chibisafe/uploads
            - ./chibisafe-database:/usr/chibisafe/database
        ports:
            - "4532:5000"
		hostname: chibisafe
        restart: unless-stopped
        environment:
            OVERWRITE_SETTINGS: "true"
            CHUNK_SIZE: 90
            ROUTE_PREFIX: /api
            RATE_LIMIT_WINDOW: 2
            RATE_LIMIT_MAX: 5
            SECRET: "wowfcgMHqZHwOIMLadWrKu3liyqPOOILpDLSDvuxq3YGhJmiZXJCVpnF96l11WfR"
            MAX_LINKS_PER_ALBUM: 5
            META_THEME_COLOR: "#20222b"
            META_DESCRIPTION: "Blazing fast file uploader edited by @rapphy243!🚀"
            META_KEYWORDS: "chibisafe,upload,uploader,file,vue,images,ssr,file uploader"
            META_TWITTER_HANDLE: "@rapphy243"
            BLOCKED_EXTENSIONS: ".msi"
            SERVER_PORT: 5000
            DOMAIN: "https://safe.rapph.dev" # Change this to the domain you are hosting this on or you will get network errors.
            SERVICE_NAME: chibisafe
            MAX_SIZE: 72727
            GENERATE_THUMBNAILS: "true"
            GENERATE_ZIPS: "true"
            STRIP_EXIF: "true" # Keep enabled or disable only if you know what you are doing
            SERVE_WITH_NODE: "true"
            GENERATED_FILENAME_LENGTH: 10
            GENERATED_ALBUM_LENGTH: 6
            PUBLIC_MODE: "false"
            USER_ACCOUNTS: "true"
            ADMIN_ACCOUNT: "admin"
            ADMIN_PASSWORD: "admin"
            DB_CLIENT: "sqlite3"
            DB_HOST: ""
            DB_USER: ""
            DB_PASSWORD: ""
            DB_DATABASE: ""
