version: "3.7"

services:
    chibisafe:
        build:
            context: ../
            dockerfile: ./docker/chibisafe/Dockerfile
        volumes:
            - ./chibisafe-data:/usr/chibisafe/uploads
            - ./chibisafe-database:/usr/chibisafe/database
        expose:
            - "5000" #Port to use to reverse proxy the container in a docker network
        restart: unless-stopped
        environment:
            OVERWRITE_SETTINGS: "false"
            CHUNK_SIZE: 90
            ROUTE_PREFIX: /api
            RATE_LIMIT_WINDOW: 2
            RATE_LIMIT_MAX: 5
            BLOCKED_EXTENSIONS: ""
            SECRET: ""
            MAX_LINKS_PER_ALBUM: 5
            META_THEME_COLOR: "#20222b"
            META_DESCRIPTION: "Blazing fast file uploader and bunker written in node! 🚀"
            META_KEYWORDS: "chibisafe,upload,uploader,file,vue,images,ssr,file uploader,free"
            META_TWITTER_HANDLE: "rapphy243"
            SERVER_PORT: 5000
            DOMAIN: "safe.example.com" #Change example.com to your own domain
            SERVICE_NAME: chibisafe
            MAX_SIZE: 5000
            GENERATE_THUMBNAILS: "true"
            GENERATE_ZIPS: "true"
            STRIP_EXIF: "true"
            SERVE_WITH_NODE: "true"
            GENERATED_FILENAME_LENGTH: 6
            GENERATED_ALBUM_LENGTH: 4
            PUBLIC_MODE: "false"
            USER_ACCOUNTS: "true"
            ADMIN_ACCOUNT: "admin"
            ADMIN_PASSWORD: "admin"
            DB_CLIENT: "sqlite3"
            DB_HOST: ""
            DB_USER: ""
            DB_PASSWORD: ""
            DB_DATABASE: ""
volumes:
    chibisafe-data:
        name: "chibisafe-data"
    chibisafe-database:
        name: "chibisafe-database"
