version: "3.7"

services:
    nginx:
        volumes:
            - nginx-data:/etc/nginx

    chibisafe:
        volumes:
            - chibisafe-data:/usr/chibisafe/uploads
            - chibisafe-database:/usr/chibisafe/database

volumes:
    nginx-data:
        name: "nginx-data"
    chibisafe-data:
        name: "chibisafe-data"
    chibisafe-database:
        name: "chibisafe-database"
